# Generated by Django 3.0.3 on 2020-03-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='id_room',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='move_x',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='room',
            name='move_y',
            field=models.IntegerField(default=None),
        ),
    ]
