# Generated by Django 3.0.3 on 2020-03-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='roomtype',
        ),
    ]
