# Generated by Django 3.0.3 on 2020-03-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_remove_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='move_x',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='room',
            name='move_y',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
