# Generated by Django 3.0.3 on 2020-03-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20200305_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomtype',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='move_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='move_y',
            field=models.IntegerField(default=0),
        ),
    ]
